TMP/Controllers/ExerciseTypesController.cs
namespace TMP.Controllers
{
    using System.Web.Mvc;
    using Attributes;
    using Domain.Entities.Exercises;
    using BLL.Services.Exercise;
    using Domain.Exceptions.Exercise;

    public class ExerciseTypesController : Controller
    {
        // GET: ExerciseTypes
        public ActionResult Index()
        {
            var service = new ExerciseTypeService(Common.Constants.Database.DBKey);
            var exerciseTypes = service.GetAll();            
            return View(exerciseTypes);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAJAXRequest]
        public ActionResult Add(ExerciseType exerciseType)
        {
            if(exerciseType != null)
            {
                var service = new ExerciseTypeService(Common.Constants.Database.DBKey);
                try
                {
                    service.AddNewExercise(exerciseType);
                }
                catch(ExerciseTypeAlreadyExists)
                {
                    return new HttpStatusCodeResult(400, "Exercise type already exists");
                }       
                catch(InvalidExerciseType)
                {
                    return new HttpStatusCodeResult(400, "Invalid exercise type");
                }         
                return new HttpStatusCodeResult(200);
            }                
            return new HttpStatusCodeResult(500);
        }

        [HttpPost]
        [ValidateAJAXRequest]
        public ActionResult IsValid(ExerciseType exerciseType)
        {
            if (exerciseType != null)
            {
                var service = new ExerciseTypeService(Common.Constants.Database.DBKey);
                if (!service.ExerciseExists(exerciseType))
                    return new HttpStatusCodeResult(200);
                else
                    return new HttpStatusCodeResult(400, "Exercise type already exists");
            }
            return new HttpStatusCodeResult(500);
        }
    }
}

TMP/Controllers/WorkoutController.cs
namespace TMP.Controllers
{
    using System.Web.Mvc;
    using Domain.Entities.Exercises;
    using Common;
    using BLL.Services.Exercise;
    using Newtonsoft.Json;

    public class WorkoutController : Controller
    {
        // GET: Workout
        public ActionResult Index()
        {
            var service = new ExerciseTypeService(Constants.Database.DBKey);
            ViewBag.AllWorkoutTypes = service.GetAll();
            return View();
        }

        [HttpGet]
        public ActionResult GetWorkoutType(string exerciseName)
        {
            var exercise = new ExerciseType {
                ExerciseName = exerciseName,
                MetricType = Domain.Entities.MetricType.DISTANCE,
                ExerciseTypeId = 1
            };
            return new JsonActionResult(exercise, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetAllWorkouts()
        {
            var service = new ExerciseTypeService(Constants.Database.DBKey);
            return new JsonActionResult(service.GetAll(), JsonRequestBehavior.AllowGet);
        }
    }
}

TMP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
        }({
            instrumentationKey:"cf9a7159-7ad1-4b5c-a76d-67a7ee82e413"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TMP/Views/Shared/_MinLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Track My Progress</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/knockout")
    @RenderSection("koscripts", required: false) 

</head>
<body class="@ViewBag.PageCSS">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Record Workout", "Index", "Workout")</li>
                    <li>@Html.ActionLink("Exercise Types", "Index", "ExerciseTypes")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">        
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Track My Progress</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TMP/Views/Shared/_StndGridLayout.cshtml
@{
    Layout = "~/Views/Shared/_MinLayout.cshtml";
}

@section koscripts {
    @RenderSection("koscripts", required: false)
}

@RenderSection("heading", required: false)

<div class="row">
    <div class="col-sm-7">
        @RenderBody()
    </div>
    <div class="col-sm-5">
        @RenderSection("rightPanel", required: false)
    </div>
</div>